name: Balena Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      architectures:
        required: true
        type: string
        description: 'Comma-separated list of architectures to build for'
    secrets:
      BALENA_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy to Balena
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install balena-cli
        env:
          BALENA_TOKEN: ${{ secrets.BALENA_TOKEN }}
        run: |
          npm install -g balena-cli
          balena login --token $BALENA_TOKEN

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and deploy for multiple architectures
        run: |
          # Define architectures to build for below.  Note, you need emulators.
          # https://docs.balena.io/reference/base-images/devicetypes/

          # Convert comma-separated string to array
          IFS=',' read -ra ARCHS <<< "${{ inputs.architectures }}"
          for arch in "${ARCHS[@]}"; do
            case $arch in
              "aarch64")
                echo "Building for aarch64..."
                balena push fyve_labs/wifi-connect-aarch64
                # this method uses emulators instead of company devices, but much slower, needs tweaks
                # balena build --deviceType raspberrypi5 --arch aarch64
                # balena deploy fyve_labs/wifi-connect-aarch64
                ;;
              "amd64")
                echo "Building for amd64..."
                balena push fyve_labs/wifi-connect-amd64
                # this method uses emulators instead of company devices, but much slower, needs tweaks
                # balena build --deviceType generic-amd64 --arch amd64
                # balena deploy fyve_labs/wifi-connect-amd64
                ;;
              *)
                echo "Unknown architecture: $arch"
                exit 1
                ;;
            esac
          done
