name: Fyve Labs Balena Deploy

on:
  push:
    branches:
      - main-fyve
  pull_request:
    types: [closed]
    branches:
      - main-fyve

jobs:
  deploy:
    name: Deploy to Balena
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semantic-release and plugins
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --no-ci

      - name: Install balena-cli
        env:
          BALENA_TOKEN: ${{ secrets.BALENA_TOKEN }}
        run: |
          npm install -g balena-cli
          balena login --token $BALENA_TOKEN

      - name: Build and deploy for multiple architectures
        run: |
          # Define architectures to build for
          # https://docs.balena.io/reference/base-images/devicetypes/
          devices=("amd64" "aarch64")
          
          for dev in "${devices[@]}"; do
            # echo "Building for $dev..."
            # balena push --deviceType $dev
            
            echo "Deploying for $dev..."
            balena push fyve_labs/wifi-connect-$dev
          done 