name: Fyve Labs Balena Deploy

on:
  push:
    branches:
      - main-fyve
  pull_request:
    types: [closed]
    branches:
      - main-fyve

jobs:
  deploy:
    name: Deploy to Balena
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semantic-release and plugins
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --no-ci

      - name: Install balena-cli
        env:
          BALENA_TOKEN: ${{ secrets.BALENA_TOKEN }}
        run: |
          npm install -g balena-cli
          balena login --token $BALENA_TOKEN

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and deploy for multiple architectures
        run: |
          # build on our known platforms (balena handles dev/arch)
          # fast/automated way to build and deploy
          # balena push fyve_labs/wifi-connect-amd64
          # balena push fyve_labs/wifi-connect-aarch64

          # Define architectures to build for below.  Note, you need emulators.
          # https://docs.balena.io/reference/base-images/devicetypes/
          balena build --deviceType generic-amd64 --arch amd64
          balena deploy fyve_labs/wifi-connect-amd64
          balena build --deviceType aarch64 --arch aarch64 
          balena deploy fyve_labs/wifi-connect-aarch64

