name: Pull Request Actions

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main-fyve

jobs:
  build-and-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/balena-deploy.yml
    with:
      architectures: "aarch64,amd64"
    secrets:
      BALENA_TOKEN: ${{ secrets.BALENA_TOKEN }} 